config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[create]
    resources :reviews, only: %i[create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :author, presence: true
  validates :stars, presence: true, numericality: { only_integer: true }, inclusion: { in: (1..5) }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @list
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: [:create]

  # POST lists/:list_id/reviews
  def create
    @list
    @review = Review.new(review_params)
    @review.list = @list
    @bookmark = Bookmark.new

    if @review.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:author, :stars, :content)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<div class="card w-50 p-4 my-4">
  <h3>Create a Bookmark</h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit class:'btn btn-success' %>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="banner text-center">
  <div class="container">
    <h1>Create a Bookmark</h1>
  </div>
</div>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render '/shared/navbar' %>
    <%= yield %>
    <%= render '/shared/footer' %>
  </body>
</html>

app/views/lists/_cards.html.erb
<div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-trip">
      <%= image_tag bookmark.movie.poster_url %>
      <div class="card-trip-infos">
        <div>
          <h2><%= bookmark.movie.title %> &#183;  <%= bookmark.movie.rating %> <i class="fa-solid fa-star"></i></h2>
          <p><%= bookmark.movie.overview %></p>
        </div>
      </div>
      <div class='card-trip-infos'>
        <h2>"<%= bookmark.comment %>"</h2>
        <h2 class="card-trip-pricing"><%= link_to "Delete",
      bookmark_path(bookmark),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/_form.html.erb
<div class="container w-50 mt-4">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/lists/_reviews.html.erb
<h2>What others think of this list..</h2>
<% if @list.reviews.empty? %>
  <p>No reviews yet.</p>
<% else %>
  <% @list.reviews.each do |review| %>
    <% review.stars.to_i.times do  %>
      <i class="fa-solid fa-star"></i>
    <% end %>
    <% (5-review.stars.to_i).times do  %>
      <i class="fa-regular fa-star"></i>
    <% end %>
    <p>"<%= review.content %>" - <%= review.author %></p>
  <% end %>
<% end %>

app/views/lists/index.html.erb
<div class="banner text-center">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>Classic</p>
  </div>
</div>
<div class="container my-4">
  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key ? list.photo.key : "vbkdy5s19ocgl1hhwrtt7uu3goar", height: 500, width: 400, crop: :fill %>')">
          <%= list.name%>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to new_list_path do %>
    <button type="button" class="my-4 btn btn-success">Create a new movie list</button>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="banner text-center">
  <div class="container">
    <h1>Create a List</h1>
  </div>
</div>
<%= render 'form' %>

app/views/lists/show.html.erb
<div class="banner text-center" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url('<%= cl_image_path @list.photo.key ? @list.photo.key : "vbkdy5s19ocgl1hhwrtt7uu3goar" %>')">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="container my-4">
  <%= render 'lists/cards' %>
</div>
<div class="container ">
  <%= render 'bookmarks/form', list: @list, bookmark: @bookmark %>
  <div class="row">
    <div class="col py-4">
      <%= render 'reviews' %>
    </div>
    <div class="col"><%= render 'reviews/form', list:@list, review:@review %></div>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="card p-4">
  <h3>Leave a Review</h3>
  <%= simple_form_for [@list, @review] do |f| %>
    <%= f.input :author %>
    <%= f.input :content, label: 'Your Review', as: :text %>
    <%= f.input :stars, collection: (1..5).to_a, label: "Rating", input_html: {data: {controller: "star-rating"}} %>
    <%= f.submit class:'btn btn-success'%>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    I <i class="fas fa-heart"></i> Movies
  </div>
</div>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-light bg-light px-4">
  <a class="navbar-brand" href="/lists"><i class="fa-solid fa-film"></i></a>
  <ul>
    <li><a class="nav-link" href="/lists">My lists</a></li>
    <li><a class="nav-link" href="/lists/new">New list</a></li>
  </ul>
</nav>